function pointLayer(ax, nodes)


        switch string(nodes.Text)
            case "Power Plant"
                geoplot(ax, nodes.NodeData,...
                    'Marker', 'o', 'MarkerSize', 7,...
                    'MarkerFaceColor','#FF513D', 'MarkerEdgeColor','#FF513D',...
                    'Tag', nodes.Text, 'displayname','Power Plants' );
            case "Cement Plant"
                geoplot(ax, nodes.NodeData,...
                    'Marker', 's', 'MarkerSize', 7,...
                    'MarkerFaceColor','#3D6AFF', 'MarkerEdgeColor','#3D6AFF',...
                    'Tag', nodes.Text,'displayname','Cement Plants' );
            case "Ethanol Plant"
                geoplot(ax, nodes.NodeData,...
                    'Marker', 'p', 'MarkerSize', 7,...
                     'MarkerFaceColor','#FFD23F', 'MarkerEdgeColor','#FFD23F',...
                    'Tag', nodes.Text, 'displayname','Ethanol Plant' );
            case "Iron and Steel Plant"
                geoplot(ax, nodes.NodeData,...
                    'Marker', '^', 'MarkerSize', 7,...
                    'MarkerFaceColor','#00A300', 'MarkerEdgeColor','#00A300',...
                    'Tag', nodes.Text,'displayname','Iron and Steel Plants'  );
            case "Injection Sites"
                geoplot(ax, nodes.NodeData,...
                    'Marker', 'o', 'MarkerSize', 10,...
                    'MarkerFaceColor','#25BE8B', 'MarkerEdgeColor','#25BE8B',...
                    'Tag', nodes.Text,'displayname','Injection Sites' );
        end


end
